# Generated by Django 4.1 on 2022-09-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Picture"
            ),
        ),
    ]
