# Generated by Django 3.2.10 on 2022-11-30 12:08

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_productcategory_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="product.productcategory",
                verbose_name="Parent",
            ),
        ),
    ]
