# Generated by Django 3.2.10 on 2022-11-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_productcategory_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=255, unique=True
            ),
        ),
    ]
