# Generated by Django 3.2.10 on 2023-01-01 14:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssignedCollectionAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(70)],
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(300)],
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="collections"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=255, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="CollectionAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=250, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "image_value",
                    models.BooleanField(
                        default=False,
                        help_text="If values for this attribute have image, select this item.",
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("oneselect", "One select"),
                            ("multiselect", "Multi Select"),
                            ("boolean", "Boolean"),
                        ],
                        default="oneselect",
                        max_length=50,
                    ),
                ),
                ("value_required", models.BooleanField(blank=True, default=False)),
            ],
            options={
                "ordering": ("slug",),
            },
        ),
        migrations.CreateModel(
            name="CollectionAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250)),
                ("picture", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="keeps hex code color value in #RRGGBBAA format",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, blank=True, max_length=255),
                ),
                ("boolean", models.BooleanField(blank=True, null=True)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="collection.collectionattribute",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("slug", "attribute")},
            },
        ),
        migrations.CreateModel(
            name="AssignedCollectionAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectionattrvalueassignment",
                        to="collection.assignedcollectionattribute",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectionvalueassignment",
                        to="collection.collectionattributevalue",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("value", "assignment")},
            },
        ),
        migrations.AddField(
            model_name="assignedcollectionattribute",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributecollection",
                to="collection.collectionattribute",
            ),
        ),
        migrations.AddField(
            model_name="assignedcollectionattribute",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="collection.collection",
            ),
        ),
        migrations.AddField(
            model_name="assignedcollectionattribute",
            name="values",
            field=models.ManyToManyField(
                blank=True,
                related_name="collectionassignments",
                through="collection.AssignedCollectionAttributeValue",
                to="collection.CollectionAttributeValue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignedcollectionattribute",
            unique_together={("collection", "attribute")},
        ),
    ]
