# Generated by Django 3.2.10 on 2023-01-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_auto_20221130_1304"),
        ("collection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignedItemAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemassignments",
                        to="collection.collectionattribute",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="collection.collection",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_type_items",
                        to="product.producttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssignedItemAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemvalueassignment",
                        to="collection.assigneditemattribute",
                    ),
                ),
                (
                    "value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itemvalueassignment",
                        to="collection.collectionattributevalue",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
                "unique_together": {("value", "assignment")},
            },
        ),
        migrations.AddField(
            model_name="assigneditemattribute",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="collection.item",
            ),
        ),
        migrations.AddField(
            model_name="assigneditemattribute",
            name="values",
            field=models.ManyToManyField(
                blank=True,
                related_name="itemproductassignments",
                through="collection.AssignedItemAttributeValue",
                to="collection.CollectionAttributeValue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assigneditemattribute",
            unique_together={("item", "assignment")},
        ),
    ]
