# Generated by Django 3.2.10 on 2023-01-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0010_alter_attributevalue_name"),
        ("collection", "0002_auto_20230110_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assigneditemattribute",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itemassignments",
                to="attribute.attributeproduct",
            ),
        ),
        migrations.AlterField(
            model_name="assigneditemattribute",
            name="values",
            field=models.ManyToManyField(
                blank=True,
                related_name="itemproductassignments",
                through="collection.AssignedItemAttributeValue",
                to="attribute.AttributeValue",
            ),
        ),
        migrations.AlterField(
            model_name="assigneditemattributevalue",
            name="value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itemvalueassignment",
                to="attribute.attributevalue",
            ),
        ),
    ]
