# Generated by Django 3.2.10 on 2023-02-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0003_auto_20230110_1434"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={},
        ),
        migrations.AddField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
