# Generated by Django 4.1 on 2022-09-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0002_alter_attribute_input_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="available_in_grid",
        ),
        migrations.RemoveField(
            model_name="attribute",
            name="filterable_in_dashboard",
        ),
        migrations.RemoveField(
            model_name="attribute",
            name="filterable_in_storefront",
        ),
        migrations.RemoveField(
            model_name="attribute",
            name="storefront_search_position",
        ),
        migrations.RemoveField(
            model_name="attribute",
            name="visible_in_storefront",
        ),
    ]
