# Generated by Django 4.1 on 2022-09-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0003_remove_attribute_available_in_grid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attributevalue",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="attributevalue",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="attributevalue",
            name="file_url",
        ),
        migrations.RemoveField(
            model_name="attributevalue",
            name="plain_text",
        ),
    ]
