# Generated by Django 4.1 on 2022-09-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0004_remove_attributevalue_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributevalue",
            name="value",
            field=models.CharField(
                blank=True,
                default="",
                help_text="keeps hex code color value in #RRGGBBAA format",
                max_length=100,
            ),
        ),
    ]
