# Generated by Django 4.1 on 2022-09-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0005_alter_attributevalue_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="image_value",
            field=models.BooleanField(
                default=False,
                help_text="If values for this attribute have image, select this item.",
            ),
        ),
    ]
