# Generated by Django 3.2.10 on 2022-11-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0008_alter_attributevalue_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=250, unique=True
            ),
        ),
    ]
