# Generated by Django 3.2.10 on 2022-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0009_alter_attribute_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attributevalue",
            name="name",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
