# Generated by Django 3.2.10 on 2023-03-08 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attribute", "0010_alter_attributevalue_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignedproductattributevalue",
            name="value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvalueassignmentvalue",
                to="attribute.attributevalue",
            ),
        ),
    ]
